name: nextcloud
version: 1.0.16
description: A Nextcloud client for dart which can use several official Nextcloud APIs
homepage: https://github.com/viktoriaschule/dart-nextcloud

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  xml: ">=3.0.0 <4.0.0"
  intl: ">=0.16.0 <0.17.0"
  http:  ">=0.12.0 <0.13.0"